# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Devan K S
title: Full-Stack Developer
email: devansamba96@gmail.com
website: devanks.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  devanks
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: devanks
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +devanks

# Additional icon links
additional_links:
  - title: Curriculum Vitae
    icon: fas fa-file-download
    url: https://tiny.one/devanCV

# About Section
about_title: <i id="about-me" href="#about-me" class="fa fa-id-card-o" aria-hidden="true"></i> About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Computer Science and Engineering graduate from NITC with a passion for challenges. I am working as a full-stack developer in Ford Smart Mobility.

  I aim to learn more about different architecture paradigms and help in designing high-quality systems. My career aim is to become a software architect.

  I am most skilled in: <mark>Spring Boot</mark> and <mark>VueJS</mark>

content:
  - title: <i id="experience" href="#experience" class="fa fa-briefcase" aria-hidden="true"></i> Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <b>Ford Smart Mobility</b>, Chennai
#        link: boringcompany.com
        sub_title: Full-Stack Developer
        caption: AUGUST 2019 - PRESENT
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Integrated Fleet Management
            * Pseudo Technical Lead role.
            * Created strict coding standards.
            * Refactor existing pipelines to Ford standard library functions for less error-prone Jenkins.
            * _Leveraged Knowledge_: Kubernetes, Jenkins, Spring Boot, VueJS
          * Ford Fleet Marketplace
            * Followed strict TDD principles.
            * Built a developer portal from base up leveraging easily editable markdown files.
            * _Leveraged Knowledge_: Spring Boot, VueJS, Webpack
          * Office Ride
            * Improved response time of an API under peak load from 12 seconds to 1.6 seconds.
            * Built a standardized Jenkins pipeline for projects with quality stages and blue-green deployment in Pivotal cloud foundry.
            * _Leveraged Knowledge_: Spring Boot, Java, Jenkins
      - layout: left
        title: <b>Salalah Methanol Company</b>, Oman
        #  link: boringcompany.com
        sub_title: IT Trainee
        caption: MAY 2018 - JULY 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Built an inventory management website in Django.
            * Helped in centralizing the data between different users.
            * Increased accountability of assets taken by users.
          * _Leveraged Knowledge_: Django framework, Python

  - title: <i id="education" href="#education" class="fa fa-graduation-cap" aria-hidden="true"></i> Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Institute of Technology, Calicut
        caption: JULY  2015 - APRIL 2019
        sub_title: B.Tech in Computer Science
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * **S grade in Software Engineering lab**: Required multiple projects to be submitted with strict adherence to Agile methodology and had to lead a team of 4 students for some of the projects.
          * **S grade in Main Course Project**: Django project using OpenCV.
  - title: <i id="projects" href="#projects" class="fa fa-desktop" aria-hidden="true"></i> Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Attendance Management System using Image Processing
        #        link: github.com/sproogen
        #        link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        quote: >
          B.Tech Main project
        description: | # this will include new lines to allow paragraphs
          * Used OpenCV to create an attendance management system to reduce the time taken for a teacher to record class attendance.
          * Build using Django web admin.
          * Students and teachers can track their class attendance with role-based authentication.
      - layout: top-middle
        title: National Service Scheme NITC Web Page
        #        link: github.com/sproogen
        #        link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #        quote: >
        #
        description: | # this will include new lines to allow paragraphs
          * A website to showcase the work of the NSS team in NITC.
          * The website can also be used to track the mandatory hours to be done as a part of course work by the students.

  - title: <i id="organizations" href="#organizations" class="fa fa-building-o" aria-hidden="true"></i> Organizations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <b>NSS</b>, Calicut
        #  link: boringcompany.com
        sub_title: Volunteer
        caption: 2016 - 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Organized multiple events in and around Kozhikode:
            * Blood donation drive.
            * SNEHARAGAM _(A talent show for developmentally challenged kids)_.
            * Help with remote government surveys.

      - layout: left
        title: <b>U&I TEACH</b>
        #        link: boringcompany.com
        sub_title: Volunteer
        caption: DECEMBER 2018 - APRIL 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * U&I Teach invests in children from underprivileged backgrounds with courses in English, Math, Science and Social Studies.
          * Helped teach underprivileged and orphan kids as a volunteer from the U&I trust.
  - title: <i id="extra-curricular-activities" href="#extra-curricular-activities" class="fa fa-bullseye" aria-hidden="true"></i> Extra-curricular Activities # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INFORMALS
        sub_title: Committee head
        caption: 2018 – 2019
#        quote: >
#
        description: | # this will include new lines to allow paragraphs
          * Committee part of the cultural festival of NITC. 
          * Handling organizing on-ground events.
          * Setup deals with bands.
      - layout: left
        title: I-Ink
        sub_title: Organizing member
        caption: 2017 – 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Literary Festival of NITC (2017)
          * Handle artists and dignitaries in the literary field with organized talks
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
