# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Devan K S
title: Backend Developer
email: devansamba96@gmail.com
website: devanks.github.io

# Social links
# twitter_username: facespics
github_username:  devanks
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: devanks
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +devanks

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Computer Science and Engineering graduate from NITC with a passion for challenges. I am working as a backend developer in Ford Smart Mobility and working towards being a full-stack developer. 
  I aim to learn more about different architecture paradigms and help in designing high-quality systems.

  I am most skilled in: <mark>Spring Boot</mark> and <mark>Java</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
