# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Devan K S
title: Full-Stack Developer
email: devansamba96@gmail.com
website: https://devanks.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  devanks
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: devanks
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +devanks

# Additional icon links
additional_links:
  - title: Curriculum Vitae
    icon: fas fa-file-download
    url: https://devanks.dev/resume

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-LJ3WGF6DDW"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <i id="about-me" href="#about-me" class="fa fa-id-card-o" aria-hidden="true"></i> About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Computer Science and Engineering graduate from NITC with a passion for challenges. I am working as a full-stack developer in Ford Smart Mobility.

  I aim to learn more about different architecture paradigms and help in designing high-quality systems. My career aim is to become a software architect.

  I am most skilled in: <mark>Spring Boot</mark> and <mark>VueJS</mark>

content:
  - title: <i id="experience" href="#experience" class="fa fa-briefcase" aria-hidden="true"></i> Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <b>Ford Smart Mobility</b>, Chennai
#        link: boringcompany.com
        sub_title: Analyst
        caption: APRIL 2021 - PRESENT
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * OCPP 2.0
            * *2 time "Top Achiever" Performance Grade* _(Scale: Top Achiever, Achiever, Lower Achiever, Unsatisfactory)_
            * Ideate and create a new architecture to better support the scalability of the OCPP platform and allow other products to connect easily to the platform.
            * Builds a microservice solution to use a charging protocol specified by OCPP
            * Created a pull request reviewable documentation repository to handle the knowledge of architecture and the team
            * Worked temporarily as a product manager handling the deliverables of the team giving insights into management flows
            * Created resources to help the extended team with Jenkins migration to new cloud space and single-handedly migrated the team's instance.
            * As a part of the Recognition program in EV, recognized twice by the wider EV team for the support provided.
            * _Leveraged Knowledge_: Scala, Play, Akka, Spring Boot, MongoDB, Kafka
          * Integrated Fleet Management
            * Pseudo Technical Lead role.
            * Created strict coding standards.
            * Refactor existing pipelines to Ford standard library functions for less error-prone Jenkins.
            * _Leveraged Knowledge_: Kubernetes, Jenkins, Spring Boot, VueJS
      - layout: left
        title: <b>Ford Smart Mobility</b>, Chennai
#        link: boringcompany.com
        sub_title: Ford College Graduate
        caption: AUGUST 2019 - APRIL 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Ford Fleet Marketplace
            * Followed strict TDD principles.
            * Built a developer portal from base up leveraging easily editable markdown files.
            * _Leveraged Knowledge_: Spring Boot, VueJS, Webpack
          * Office Ride
            * Improved response time of an API under peak load from 12 seconds to 1.6 seconds.
            * Built a standardized Jenkins pipeline for projects with quality stages and blue-green deployment in Pivotal cloud foundry.
            * _Leveraged Knowledge_: Spring Boot, Java, Jenkins
      - layout: left
        title: <b>Salalah Methanol Company</b>, Oman
        #  link: boringcompany.com
        sub_title: IT Trainee
        caption: MAY 2018 - JULY 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Built an inventory management website in Django.
            * Helped in centralizing the data between different users.
            * Increased accountability of assets taken by users.
          * _Leveraged Knowledge_: Django framework, Python

  - title: <i id="education" href="#education" class="fa fa-graduation-cap" aria-hidden="true"></i> Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Institute of Technology, Calicut
        caption: JULY  2015 - APRIL 2019
        sub_title: B.Tech in Computer Science
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          * **S grade in Software Engineering lab**: Required multiple projects to be submitted with strict adherence to Agile methodology and had to lead a team of 4 students for some of the projects.
          * **S grade in Main Course Project**: Django project using OpenCV.
  - title: <i id="projects" href="#projects" class="fa fa-desktop" aria-hidden="true"></i> Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Attendance Management System using Image Processing
        link: https://github.com/devanks/AttendanceMgmtAI
        link_text: Project Repository
        icon: fab fa-github
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        quote: >
          B.Tech Main project
        description: | # this will include new lines to allow paragraphs
          * Used OpenCV to create an attendance management system to reduce the time taken for a teacher to record class attendance.
          * Build using Django web admin.
          * Students and teachers can track their class attendance with role-based authentication.
      - layout: top-middle
        title: National Service Scheme NITC Web Page
        #        link: github.com/sproogen
        #        link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #        quote: >
        #
        description: | # this will include new lines to allow paragraphs
          * A website to showcase the work of the NSS team in NITC.
          * The website can also be used to track the mandatory hours to be done as a part of course work by the students.

  - title: <i id="organizations" href="#organizations" class="fa fa-building-o" aria-hidden="true"></i> Organizations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <b>NSS</b>, Calicut
        #  link: boringcompany.com
        sub_title: Volunteer
        caption: 2016 - 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Organized multiple events in and around Kozhikode:
            * Blood donation drive.
            * SNEHARAGAM _(A talent show for developmentally challenged kids)_.
            * Help with remote government surveys.

      - layout: left
        title: <b>U&I TEACH</b>
        #        link: boringcompany.com
        sub_title: Volunteer
        caption: DECEMBER 2018 - APRIL 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * U&I Teach invests in children from underprivileged backgrounds with courses in English, Math, Science and Social Studies.
          * Helped teach underprivileged and orphan kids as a volunteer from the U&I trust.
  - title: <i id="extra-curricular-activities" href="#extra-curricular-activities" class="fa fa-bullseye" aria-hidden="true"></i> Extra-curricular Activities # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INFORMALS
        sub_title: Committee head
        caption: 2018 – 2019
#        quote: >
#
        description: | # this will include new lines to allow paragraphs
          * Committee part of the cultural festival of NITC. 
          * Handling organizing on-ground events.
          * Setup deals with bands.
      - layout: left
        title: I-Ink
        sub_title: Organizing member
        caption: 2017 – 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products #like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Literary Festival of NITC (2017)
          * Handle artists and dignitaries in the literary field with organized talks
  - title: <i id="skills" href="#skills" class="fa fa-hammer" aria-hidden="true"></i> Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <table class="table table-no-border">
        <tbody>
          <tr>
            <td>
              <img alt="Spring" src="https://img.shields.io/badge/spring-%236DB33F.svg?style=for-the-badge&amp;logo=spring&amp;logoColor=white" />
            </td>
            <td class="rating-4">
            </td>
            <td>
              <img alt="VueJS" src="https://img.shields.io/badge/Vue.js-35495E?style=for-the-badge&logo=vuedotjs&logoColor=4FC08D" />
            </td>
            <td class="rating-4">
            </td>
          </tr>
          <tr>
            <td>
              <img alt="Java" src="https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=java&logoColor=white" />
            </td>
            <td class="rating-5">
            </td>
            <td>
              <img alt="JavaScript" src="https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E" />
            </td>
            <td class="rating-3">
            </td>
          </tr>
          <tr>
            <td>
              <img alt="Django" src="https://img.shields.io/badge/Django-092E20?style=for-the-badge&logo=django&logoColor=green" />
            </td>
            <td class="rating-2">
            </td>
            <td>
              <img alt="Kubernetes" src="https://img.shields.io/badge/kubernetes-326ce5.svg?&style=for-the-badge&logo=kubernetes&logoColor=white" />
            </td>
            <td class="rating-1">
            </td>
          </tr>
        </tbody>
      </table>

#  - title: <i id="linkedin-section" href="#linked-in-section" class="fab fa-linkedin-in" aria-hidden="true"></i> LinkedIn # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" {% if site.darkmode == true and site.darkmode != 'never' %}data-theme="dark"{% endif %} data-type="VERTICAL" data-vanity="devanks" data-version="v1"> <a class="badge-base__link LI-simple-link" href="https://in.linkedin.com/in/devanks?trk=profile-badge"> Devan K S </a> </div>
              

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from
